import json
import httpx
from llm.base import BaseLLMProvider


class ClaudeProvider(BaseLLMProvider):
    _API_URL = 'https://api.anthropic.com/v1/messages'

    def __init__(self, api_key: str, model: str = 'claude-sonnet-5'):
        self.api_key = api_key
        self.model = model

    def _headers(self) -> dict:
        return {
            'x-api-key': self.api_key,
            'anthropic-version': '2023-06-01',
            'content-type': 'application/json',
        }

    def _payload(self, messages: list[dict], stream: bool = False) -> dict:
        payload = {
            'model': self.model,
            'max_tokens': 1024,
            'messages': messages,
        }
        if stream:
            payload['stream'] = True
        return payload

    def chat(self, messages: list[dict]) -> str:
        try:
            resp = httpx.post(
                self._API_URL,
                headers=self._headers(),
                json=self._payload(messages),
                timeout=30,
            )
            resp.raise_for_status()
            return resp.json()['content'][0]['text']
        except Exception as e:
            return f"Claude error: {e}"

    def chat_stream(self, messages: list[dict]):
        """Yield response text chunks as they are generated by the LLM."""
        try:
            with httpx.stream(
                'POST',
                self._API_URL,
                headers=self._headers(),
                json=self._payload(messages, stream=True),
                timeout=30,
            ) as response:
                response.raise_for_status()
                for line in response.iter_lines():
                    if not line.startswith('data: '):
                        continue
                    event = json.loads(line[len('data: '):])
                    if event.get('type') == 'content_block_delta':
                        delta = event.get('delta', {})
                        if delta.get('type') == 'text_delta':
                            yield delta.get('text', '')
        except Exception as e:
            yield f"\n\n[Claude error: {e}]"
