import json
import httpx
from llm.base import BaseLLMProvider


class ClaudeProvider(BaseLLMProvider):
    def __init__(self, api_key: str, model: str = 'claude-sonnet-5'):
        self.api_key = api_key
        self.model = model

    def chat(self, messages: list[dict]) -> str:
        try:
            resp = httpx.post(
                'https://api.anthropic.com/v1/messages',
                headers={
                    'x-api-key': self.api_key,
                    'anthropic-version': '2023-06-01',
                    'content-type': 'application/json',
                },
                json={
                    'model': self.model,
                    'max_tokens': 1024,
                    'messages': messages,
                },
                timeout=30,
            )
            resp.raise_for_status()
            return resp.json()['content'][0]['text']
        except Exception as e:
            return f"Claude error: {e}"

    def chat_stream(self, messages: list[dict]):
        """Yield response text chunks as they are generated by the LLM."""
        try:
            with httpx.stream(
                'POST',
                'https://api.anthropic.com/v1/messages',
                headers={
                    'x-api-key': self.api_key,
                    'anthropic-version': '2023-06-01',
                    'content-type': 'application/json',
                },
                json={
                    'model': self.model,
                    'max_tokens': 1024,
                    'messages': messages,
                    'stream': True,
                },
                timeout=30,
            ) as response:
                response.raise_for_status()
                for line in response.iter_lines():
                    if not line.startswith('data: '):
                        continue
                    event = json.loads(line[len('data: '):])
                    if event.get('type') == 'content_block_delta':
                        delta = event.get('delta', {})
                        if delta.get('type') == 'text_delta':
                            yield delta.get('text', '')
        except Exception as e:
            yield f"\n\n[Claude error: {e}]"
